"""Recruitment data access layer — re-exports from repository_impl."""

from app.modules.recruitment.repository_impl import (
    create_employee,
    create_mapping,
    delete_mapping,
    find_employee_by_email,
    generate_client_code,
    generate_position_code,
    get_candidate,
    get_client,
    get_mapping,
    get_position,
    link_employee_user,
    list_clients,
    log_activity,
    move_stage,
    next_seq,
    recompute_position_seats,
    set_seq,
    update_candidate_current_stage,
)

__all__ = [
    "create_employee",
    "create_mapping",
    "delete_mapping",
    "find_employee_by_email",
    "generate_client_code",
    "generate_position_code",
    "get_candidate",
    "get_client",
    "get_mapping",
    "get_position",
    "link_employee_user",
    "list_clients",
    "log_activity",
    "move_stage",
    "next_seq",
    "recompute_position_seats",
    "set_seq",
    "update_candidate_current_stage",
]
