"""Recruitment domain constants."""

from app.modules.recruitment.enums.department import Department

ROLES_BY_CATEGORY = {
    Department.service: [
        "Bar Assistant",
        "Bar Manager",
        "Bar Supervisor",
        "Barback",
        "Barista",
        "Bartender",
        "Café Manager",
        "Café Supervisor",
        "Captain",
        "Cashier",
        "Counter Sales",
        "Duty Manager",
        "F&B Executive",
        "F&B Supervisor",
        "Floor Supervisor",
        "Front Office Executive",
        "GRE",
        "Hostess",
        "Mixologist",
        "Outlet Manager",
        "Shift Manager",
        "Sommelier",
        "Steward",
        "Waiter / Server",
        "RM",
        "ARM",
        "Head Bartender",
        "Beverage Head",
    ],
    Department.boh: [
        "CDP",
        "Commi 1",
        "Commi 2",
        "Commi 3",
        "DCDP",
        "Executive Chef",
        "Food Production Manager",
        "Head Baker",
        "Head Chef",
        "Kitchen Supervisor",
        "Packaging Assistant",
        "Sous Chef",
        "Staff Cook",
        "Store Manager",
        "Storekeeper",
    ],
    Department.corporate: [
        "Accountant / Accounts",
        "Admin / Back Office",
        "Brand Manager",
        "Business Development",
        "Community Manager",
        "Content Strategist",
        "CRM",
        "Data Analyst",
        "EA / PA",
        "F&B Controller",
        "General Manager",
        "Graphic Designer",
        "HR",
        "Lawyer",
        "Marketing",
        "MIS Executive",
        "Operations Head",
        "Payroll",
        "PR",
        "Project Manager",
        "Purchase",
        "Sales",
        "Social Media",
        "Supply Chain / SCM",
        "Training Manager / L&D",
    ],
}
